🚀 Toast스타일, 기능 컴포넌트 입니다.
codeit-sprint-part2-2team/rolling pull request #121
Opened 2024-10-29 07:51 UTC by yongcheol-1

### 80

close #'80'

### 변경 사항 요약 

Toast 스타일, 기능 컴포넌트 입니다.

### 테스트 결과 
![Toast 테스트 캡처](https://github.com/user-attachments/assets/c944362d-5848-4486-a3f3-3d0313aa204c)

2024-10-29 08:01 UTC, junghwa1996 commented
- PR 본문 이슈 연결 안된것같아용 ' ' 이거빼고 하시면 될것같네용
- 그리고 병합 에러 있네요~ 최신 브랜치 머지 받고, 컴플릿 나는 부분 해결해서 재푸시 해주세요

2024-10-29 08:20 UTC, junghwa1996 requested changes
지금 컴포넌트가 URL 복사를 했을때만 토스트가 띄어주는것같은데, 확장성을 위해서 분리해서 컴포넌트 작업하시는게 어떨까요?
```javascript
Toast.jsx // 이벤트 핸들러를 받아서 토스트 오픈 여부를 리턴하는 컴포넌트
ToastMessages.jsx // 토스트 메세지 스타일 컴포넌트
CopyUrl.jsx // 이벤트 핸들러를 받아서 현재의 URL을 리턴하는 기능 컴포넌트
```
이렇게요~

그리고 해당 토스트 라이브러리 사용 부분이 안보이는데 스타일만 가져오는 라이브러리를 사용하신걸까요?? 그런거라면 기능구현이 되어있는 라이브러리로 찾으시거나 기능을 별도로 만드시면 될것같아용

2024-10-29 08:20 UTC, junghwa1996 commented on src/assets/close.svg
아이콘 네이밍은 `icon-` 으로 시작해주세요

2024-10-29 08:20 UTC, junghwa1996 commented on src/assets/completed.svg
아이콘 네이밍은 `icon-` 으로 시작해주세요

2024-10-29 08:20 UTC, junghwa1996 commented on src/components/toast/ToastComponent.jsx
> +`;
스타일 컴포넌트는 따로 파일 생성해서 import 해서 사용해주세요~

2024-10-29 08:20 UTC, junghwa1996 commented on src/pages/HomePage/HomePage.jsx
테스트 하신건 커밋하지 말아주세용

2024-10-29 08:20 UTC, junghwa1996 commented on src/components/toast/ToastComponent.jsx
> +const StyledToastContainer = styled(ToastContainer)`
네이밍 컨벤션으로 앞에 `StyledToastContainer`보다는 `ToastContainer`가 적절할것같아용

2024-10-29 08:20 UTC, junghwa1996 commented on src/components/toast/ToastComponent.jsx
> +  color: white;
`theme`로 가져와서 사용해주세용 #fff 색상이 이미 이썽용

2024-10-29 08:20 UTC, junghwa1996 commented on src/components/toast/ToastComponent.jsx
> +  font-size: 1rem;
해당 시안은 `16px`이에용 수정해주세용 `1.6rem`으로!
그리고 해당 부분도 `theme` 이용해주세용

2024-10-29 08:20 UTC, junghwa1996 commented on src/components/toast/ToastComponent.jsx
> +  overflow: hidden; /* 내용이 잘리지 않도록 설정 */
해당 주석이 오히려 가독성을 해치는것같아요ㅠㅠ 주석 제거해주세요!

2024-10-29 08:20 UTC, junghwa1996 commented on src/components/toast/ToastComponent.jsx
> +  const urlToCopy = 'https://your-custom-url.com'; // 복사할 URL 설정
이 URL 변수는 저희가 해당 함수 파라미터로 전달받아서 넘겨줘야할것같아요~ 파라미터로 설정해주세요!

2024-10-29 23:24 UTC, Hogn-hyeonbin approved these changes
확인했습니다

2024-10-30 04:03 UTC, yongcheol-1 commented
수정 사항 반영해서 업데이트 했습니다.

2024-10-30 05:59 UTC, junghwa1996 requested changes
수정사항 너무 잘반영해주셨네용

2024-10-30 05:59 UTC, junghwa1996 commented on src/components/toast/Toast.jsx
> + */
되도록이면 이거는 문서 최상단에 넣어주세요~ 이거는 추후 리팩토링할때 해주시면 됩니다 확인댓글달아주시면 승인할게요

2024-10-30 05:59 UTC, swp91 approved these changes
토스트 확인했습니다

2024-10-30 06:02 UTC, junghwa1996 commented on src/components/toast/Toast.jsx
> + */
@yongcheol-1  확인하시면 댓글 남겨주세용 알람이 안와용

2024-10-30 06:06 UTC, yongcheol-1 commented on src/components/toast/Toast.jsx
> + */
넵 좋은 피드백과 수정사항 감사합니다.

2024-10-30 06:11 UTC, junghwa1996 approved these changes

2024-10-30 07:59 UTC, merged