✨ Simplebanner 이모지 선택기능 추가
codeit-sprint-part2-2team/rolling pull request #159
Opened 2024-10-30 14:36 UTC by yongcheol-1

### 이슈 번호

close #158 

### 변경 사항 요약

이모지 선택기능을 추가했습니다.

횟수에 따라 정렬되도록 기능추가 했습니다.

최대8개까지만 나오도록 했습니다.

Button 스타일 수정이 필요합니다.

### 테스트 결과

![EmojiPicker 캡처](https://github.com/user-attachments/assets/67428447-9a9e-4433-b6c2-f4918adee2ea)

2024-10-30 15:09 UTC, junghwa1996 commented
용철님 혹시 제가 방금 푸시했는데, 그거 풀 받기전에 vscode 한번 껏다가 다시 키셔서 풀받고 해당 브랜치에 다시 머지하고 커밋올려봐주시겠어요?
지금 ESLint 규칙이 적용이 안되고계신것같아서 확인한번해봐야할것같아용

2024-10-30 15:18 UTC, yongcheol-1 commented
다시 했습니다!

2024-10-30 15:21 UTC, junghwa1996 commented
![스크린샷 2024-10-31 오전 12 20 41](https://github.com/user-attachments/assets/cfd2e465-2382-46c3-bab4-b8e8f3e20943)
혹시 이 에러 안뜨세요?

2024-10-30 15:23 UTC, junghwa1996 commented
> 다시 했습니다!

조거 에러 안뜨시는걸까요? 터미널에서??

2024-10-30 15:40 UTC, junghwa1996 requested changes
`npx prettier --write .`
이거 한번만 돌려주시고 변경사항 푸시하시면 답글주세요!

2024-10-30 16:52 UTC, yongcheol-1 commented
네 에러안뜨고 푸쉬되었어요!

2024-10-30 16:54 UTC, junghwa1996 approved these changes

2024-10-30 16:56 UTC, swp91 approved these changes
확인했습니다 👍

2024-10-31 07:59 UTC, junghwa1996 commented
이거는 언제 머지하나용?

2024-10-31 23:51 UTC, junghwa1996 commented
제가 재수정중입니당~

2024-11-01 01:10 UTC, junghwa1996 commented
동작 가능하게 스타일링까지 했습니다~ 확인하시고 댓글 남겨주시구요 나중에 TODO랑 REVIEW 달아 놨으니 확인하세요~ @yongcheol-1

2024-11-01 01:11 UTC, junghwa1996 requested changes
동작 가능하게 스타일링까지 했습니다~ 확인하시고 댓글 남겨주시구요 나중에 TODO랑 REVIEW 달아 놨으니 확인하세요~ @yongcheol-1

2024-11-01 03:29 UTC, yongcheol-1 commented
넵 확인했습니다.

2024-11-01 05:04 UTC, junghwa1996 approved these changes

2024-11-01 05:04 UTC, merged