#143 ✨ 헤더 레이아웃 작업
codeit-sprint-part2-2team/rolling pull request #165
Opened 2024-10-31 07:32 UTC by swp91

### 이슈 번호

close #143 

### 변경 사항 요약

페이지 마다 필요에따라 조건부로 보여주는 헤더 레이아웃입니다.

### 테스트 결과

의도대로 잘 작동됩니다.

### 사용예시
![image](https://github.com/user-attachments/assets/97255dff-ed54-4e3d-b2d7-f8e55c79c13b)

### 참고사항

아직 헤더 안에 들어가는 다른 컴포넌들이 작업이 덜 끝난것들이 있어서 일단 아이템 임시로 채워놓았습니다.
추후 조립할때 추가작업 예정입니다.

2024-10-31 08:07 UTC, junghwa1996 requested changes

2024-10-31 08:07 UTC, junghwa1996 commented on src/layout/Header/Header.jsx
> +  const VIEW = useDeviceType();
VIEW 보다는 감지 기능이니까 isDeviceType 이 더 좋을것같아요!

2024-10-31 08:07 UTC, junghwa1996 commented on src/layout/Header/Header.jsx
> +function Header({ hide = false, two = false }) {
좀 더 직관적인 이름이 좋을것같아요! 아까 멘토님이 말씀하셨던 type을 이용해도 좋을것같네요!
`"default" | "button" | "banner"`
이런 식으루여!

2024-10-31 08:07 UTC, junghwa1996 commented on src/layout/Header/Header.styles.js
위에 남긴 리뷰 확인해보시고 여러값을 받는거보다는 한번에 type으로 관리하는게 더 좋을것같습니다!

2024-10-31 08:07 UTC, junghwa1996 commented on src/layout/Header/Header.jsx
> +    </HeaderArea>
여기도 type으로 한번에 HeaderArea 컴포넌트 파라미터로 받아서 관리하면 더 좋을것같아요!

2024-10-31 09:13 UTC, swp91 commented on src/layout/Header/Header.jsx
> +  const VIEW = useDeviceType();
넵 감사합니다 상수는 올대문자 써야된다는 네이밍규칙대로 가고있었는데 좀 자유롭게 가보겠습니다!

2024-10-31 09:30 UTC, swp91 commented on src/layout/Header/Header.jsx
> +function Header({ hide = false, two = false }) {
넵 이름을 너무 단순하게 짠것같네요 직관적으로 수정하였습니다 감사합니다!

2024-10-31 09:31 UTC, swp91 commented on src/layout/Header/Header.styles.js
확실히 이렇게 관리하니까 훨씬 깔끔한것같습니다 감사합니다!👍

2024-10-31 09:31 UTC, swp91 commented on src/layout/Header/Header.jsx
> +    </HeaderArea>
넵 요기두 수정완료하였습니다

2024-10-31 09:37 UTC, junghwa1996 commented on src/layout/Header/Header.jsx
> +  const VIEW = useDeviceType();
해당 변수는 리턴되는 값이 pc인지 mo인지 다르게 리턴되기때문에 상수는 아닙니당

2024-10-31 09:37 UTC, junghwa1996 commented on src/layout/Header/Header.jsx
> +  const VIEW = useDeviceType();
상수는 말그대로 이미지 처럼 '불변인 값' 이에요!

2024-10-31 09:38 UTC, swp91 commented on src/layout/Header/Header.jsx
> +  const VIEW = useDeviceType();
아 그렇죠! 착각했습니다 감사합니다

2024-10-31 09:45 UTC, junghwa1996 requested changes

2024-10-31 09:45 UTC, junghwa1996 commented on src/layout/Header/Header.jsx
> +        <InfoHeader {...headerProps}>
여기는 그냥 `type={type}` 으로만 가셔도 될것같습니다~ 나머지 props는 기능 개발자가 조정할수있도록 하는게 좋을듯하네요! 해당 타입만 스타일에 영향을 미치는거라 굳이 다른 props를 받아올 필요는 없을것같아요!

2024-10-31 09:48 UTC, swp91 commented on src/layout/Header/Header.jsx
> +        <InfoHeader {...headerProps}>
아하 넵 반응형 스타일떄문에 모바일 크기에서 사라지거나 2줄로 변경되는 부분떄문에 디바이스타입을 넣었던거였거든요 그러면 그냥 다 빼고 타입만 넣어드리는걸로갈까요?

2024-10-31 10:22 UTC, junghwa1996 commented on src/layout/Header/Header.jsx
> +        <InfoHeader {...headerProps}>
디바이스 크기 훅은 어차피 기능개발 하시는분도 사용하셔야되니 그부분은 그냥 두고 저 prop만 넘겨주면될것같아요~ 안에 만들어놓으신 더미들은 나중에 함수 컴포넌트들로 채워지면서 수정될테니까용

2024-10-31 21:51 UTC, swp91 commented on src/layout/Header/Header.jsx
> +        <InfoHeader {...headerProps}>
넵 감사합니다 말씀하신 부분 반영하였습니다

2024-10-31 22:09 UTC, junghwa1996 requested changes

2024-10-31 22:09 UTC, junghwa1996 commented on src/layout/Header/Header.jsx
> +          </div>
엥 디바이스 왜지우셨나용?? 이거는 모바일에서 안보여지지않난여? 그건 하셔야대영

2024-10-31 22:24 UTC, swp91 commented on src/layout/Header/Header.jsx
> +          </div>
넵 이부분은 다시 살렸습니다 감사합니다~

2024-10-31 22:48 UTC, junghwa1996 requested changes
## 이슈
![스크린샷 2024-11-01 오전 7 46 21](https://github.com/user-attachments/assets/21f45c4a-af5a-4913-8aa0-c8463ad27263)
## 상세
- doubleLine border값 없음, 내부 max-width 잡아줘야할것같아용
- 버튼은 어디에있져...?

2024-11-01 04:20 UTC, swp91 commented
버튼누락, 보더라인 누락 수정완료하였습니다.

2024-11-01 09:23 UTC, junghwa1996 approved these changes
👍🏻👍🏻👍🏻

2024-11-01 14:39 UTC, mangmang1004 approved these changes

2024-11-01 14:39 UTC, mangmang1004 commented on src/layout/Header/MainHeader.styles.js
> +    padding: 0 15px;
이제 styled component 마스터 하신 거 같네융 !! 수고하셨숩니다 🙏🏻

2024-11-01 21:10 UTC, swp91 commented
이거는 어프로브 주시면 테스팅 지운다음에 머지하고 헤더 조립작업은 #195  에서 하겠습니다

2024-11-01 21:36 UTC, junghwa1996 approved these changes

2024-11-01 21:40 UTC, merged