#146 롤링 페이퍼 생성 페이지
codeit-sprint-part2-2team/rolling pull request #175
Opened 2024-10-31 10:58 UTC by hwiiron

### 이슈 번호

close #146 

### 변경 사항 요약

- [x] 받는 사람 이름
- [x] 배경화면 선택
- [x] post 요청으로 생성

- 배경화면은 선택하지 않아도 기본 값으로 첫번째 컬러로 설정되므로, 받는 사람 이름 Input만 체크하여 생성하기 버튼 활성화/비활성화 되도록 구현하였습니다.
- 생성하기 완료 시 생성된 롤링페이퍼로 이동하게 구현하였습니다.
- 여러가지의 경우로 post 요청까지 정상적으로 동작하는 테스트까지 완료했습니다.

추가로 post 요청 보낼 시, 컬러가 아닌 이미지를 선택했을 경우에도 post 요청 데이터에 `backgroundColor` 값을 보내야지만 요청 성공하더라구요,, 이 부분은 그래서 이미지 선택했을 경우에도 기본 값으로 `beige`로 설정되게 처리했습니다.

### 테스트 결과
<img width="678" alt="스크린샷 2024-10-31 18 27 57" src="https://github.com/user-attachments/assets/41a5cf52-66ab-40c6-bd43-1bb56f0a2c09">
<img width="669" alt="스크린샷 2024-10-31 18 28 12" src="https://github.com/user-attachments/assets/e96b28d5-fa9a-43b4-b3d9-061f33abf9df">

2024-10-31 11:25 UTC, junghwa1996 requested changes
### 이슈
![스크린샷 2024-10-31 오후 8 20 15](https://github.com/user-attachments/assets/d741e2e9-f2a5-49ee-9a4c-a09ae304d9c0)

## 이슈재현
- 이미지 선택 부분을 여러번 반복해서 클릭하니 뜸
## 내용
- api 요청에 에러와 로딩 구문이 필요할것같아요
- 선택할때마다 에러떠서 리뷰 진행이 불가합니다!

2024-10-31 11:35 UTC, hwiiron commented
> ### 이슈
> ![스크린샷 2024-10-31 오후 8 20 15](https://private-user-images.githubusercontent.com/59001439/381928274-d741e2e9-f2a5-49ee-9a4c-a09ae304d9c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNzQ0NDMsIm5iZiI6MTczMDM3NDE0MywicGF0aCI6Ii81OTAwMTQzOS8zODE5MjgyNzQtZDc0MWUyZTktZjJhNS00OWVlLTlhNGMtYTA5YWUzMDRkOWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDExMjkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZjEzMzZjZTdjODA2YTJkMDlmMTM4OTZkZDVlODk5ODRiYjgyZWQzZjZmYjgwNmZjOTkzNmViM2VjNjQ1Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jsqqJs1fAjvvNEc8-3m1fm25lC1phcgJgBUZWg63M1k)
> 
> ## 이슈재현
> * 이미지 선택 부분을 여러번 반복해서 클릭하니 뜸
> 
> ## 내용
> * api 요청에 에러와 로딩 구문이 필요할것같아요
> * 선택할때마다 에러떠서 리뷰 진행이 불가합니다!

테스트 해주신 페이지는 메시지 생성 페이지로 DropDown 컴포넌트의 button태그에 `type="button"`으로 지정하지 않아서 생긴 문제입니다.
type 지정은 @mangmang1004 소망님께 요청드려둔 상태입니다!

`api 요청에 에러와 로딩 구문이 필요할것같아요` 적어주신 내용은 적용하도록 하겠습니다!

2024-10-31 11:36 UTC, hwiiron commented
테스트 해주신 페이지는 메시지 생성 페이지로 DropDown 컴포넌트의 button태그에 `type="button"`으로 지정하지 않아서 생긴 문제입니다.
type 지정은 @mangmang1004 소망님께 요청드려둔 상태입니다!

`api 요청에 에러와 로딩 구문이 필요할것같아요` 적어주신 내용은 적용하도록 하겠습니다!

2024-10-31 11:52 UTC, junghwa1996 approved these changes

2024-10-31 11:52 UTC, junghwa1996 commented on src/components/BackgroundSelector/RadioCard.styles.js
> +    transform: translate(-50%, -50%) scale(1); /* 원래 크기로 확대 */
여기 부분 어떻게 구현되었는지 나중에 오류 해결되면 보고싶네용 ㅎㅎ 👍🏻

2024-10-31 11:54 UTC, hwiiron commented on src/components/BackgroundSelector/RadioCard.styles.js
> +    transform: translate(-50%, -50%) scale(1); /* 원래 크기로 확대 */
별거 아니지만 살짝 추가해봤습니다...ㅎㅎ

2024-11-01 02:06 UTC, swp91 approved these changes

2024-11-01 02:06 UTC, swp91 commented on src/pages/RecipientsAdd/RecipientsAddPage.jsx
> +      // 컬러가 선택되었을 땐, backgroundColor가 null 값이어야 함.
주석 부분만 정리해주시면 좋을것같습니다 👍

2024-11-01 02:41 UTC, hwiiron commented on src/pages/RecipientsAdd/RecipientsAddPage.jsx
> +      // 컬러가 선택되었을 땐, backgroundColor가 null 값이어야 함.
확인했습니다! 제가 이 부분 작업하면서 좀 복잡하게 작업이 된 것 같아서 주석 설명을 달아뒀는데 주석 내용들은 전체적으로 한 번에 정리하도록 하겠습니다!!👍

2024-11-01 02:43 UTC, merged