📝 ✨ 무한 스크롤 기능 컴포넌트 추가
codeit-sprint-part2-2team/rolling pull request #177
Opened 2024-10-31 14:25 UTC by Hogn-hyeonbin

#176 무한 스크롤 기능

InfiniteScroll.jsx 파일 추가 - Intersection Observer API라이브러리 사용

Test_MessagesEditPage.jsx 파일 코드 중

`const {`
    `data: messageData,`
  `  loading: messageLoading,`
  `  error: messageError,`
`  } = useFetchData(() => getMessagesList(currentId), [currentId]);` 

> 수정

` const [page, setPage] = useState(1);  `
 ` const [messages, setMessages] = useState([]); ` 
  `const [hasMore, setHasMore] = useState(true); `
  `const [loading, setLoading] = useState(false); `

> 이유
데이터 중복 요청 방지
상태 관리 통일성으로  fetchMessages 함수는 페이지네이션을 처리하고 메시지를 상태에 추가하는 방식으로 동작하기 떄문에 messageData를 사용하기보다는 messages 상태를 사용하여 일관성을 유지.

테스트는 못했습니다.
테스트를 하기에 문제가 많았습니다.....

2024-10-31 22:49 UTC, junghwa1996 commented
지금은 테스트 진행중이시겠져?

2024-11-01 02:08 UTC, swp91 approved these changes
인터섹션 옵저버 요렇게 쓰는거군요 잘봤습니다!
나중에 시간되면 로딩중일때 동그라미 같은 애니메이션 넣으면 좋을것같습니다!

2024-11-01 02:09 UTC, junghwa1996 commented
> 인터섹션 옵저버 요렇게 쓰는거군요 잘봤습니다! 나중에 시간되면 로딩중일때 동그라미 같은 애니메이션 넣으면 좋을것같습니다!

이거 지금 동작하지않는 코드 입니다 성우님도 확인 한번 해주세요

2024-11-01 02:12 UTC, swp91 commented
앗 그렇군요 코드만 봤는데 확인해보겠습니다

2024-11-01 02:34 UTC, junghwa1996 requested changes
해당 스크롤 함수 데이터 동작 부분에 연결해두었어요
보니까 새로운 데이터를 요청하는 함수가 작성이 안되어있더라구요
제가 TODO 로 표기해놨으니 해당 기능 완료하고 노티 주세요

2024-11-01 02:36 UTC, Hogn-hyeonbin commented
넵 알겠습니다!

2024-11-01 03:14 UTC, junghwa1996 commented
fix #188 작업해서 푸시했습니다 풀 받아주세요

2024-11-01 03:20 UTC, Hogn-hyeonbin commented
전 풀 완료 했습니다

2024-11-01 03:21 UTC, junghwa1996 commented
> 전 풀 완료 했습니다

앞으로 해당 커밋에 메세지 남기실때는 이렇게 해주세용~

2024-11-01 03:23 UTC, junghwa1996 commented
> > 전 풀 완료 했습니다
> 
> 앞으로 해당 커밋에 메세지 남기실때는 이렇게 해주세용~

#188 원격브랜치 삭제 완료

2024-11-01 16:47 UTC, junghwa1996 commented
여기는 커밋이 안올라오는것같은데 현빈님!! 이거 언제쯤 될까요?

2024-11-01 17:44 UTC, Hogn-hyeonbin commented
4시이내로 끝내겠습니다

2024-11-01 19:32 UTC, Hogn-hyeonbin commented
> 여기는 커밋이 안올라오는것같은데 현빈님!! 이거 언제쯤 될까요?
완료했습니다!

2024-11-02 13:42 UTC, junghwa1996 commented
이거 머지 안된거죠? @Hogn-hyeonbin

2024-11-02 13:52 UTC, junghwa1996 commented
지금 컴플리트 나서 해결중입니다~ 기다려주세요

2024-11-02 14:22 UTC, junghwa1996 commented
이거 작업이 된거 맞나요?? @Hogn-hyeonbin

2024-11-02 14:24 UTC, Hogn-hyeonbin commented
지금 오류 발생한 부분 찾은 것 같아서 수정하면서 구현 상태 확인 중이어서 좀 있으면 끝날 것 같습니다

2024-11-02 14:24 UTC, junghwa1996 commented
> 지금 오류 발생한 부분 찾은 것 같아서 수정하면서 구현 상태 확인 중이어서 좀 있으면 끝날 것 같습니다

파일 최신화먼저 해주시고 컴플릿도 해결해서 다시 요청주세요!

2024-11-02 17:39 UTC, Hogn-hyeonbin commented
> 파일 최신화먼저 해주시고 컴플릿도 해결해서 다시 요청주세요!
일단 컴플리트 오류 안나게 코드 수정 했습니다 확인 부탁 드립니다 !

2024-11-02 17:47 UTC, junghwa1996 commented
> > 파일 최신화먼저 해주시고 컴플릿도 해결해서 다시 요청주세요!
> > 일단 컴플리트 오류 안나게 코드 수정 했습니다 확인 부탁 드립니다 !

오잉 지금 하단에 `This branch has conflicts that must be resolved` 이거 아직도 떠있어요! 해결해주세요!

2024-11-02 19:06 UTC, Hogn-hyeonbin commented
> 오잉 지금 하단에 `This branch has conflicts that must be resolved` 이거 아직도 떠있어요! 해결해주세요!

죄송합니다...다시 수정해 오겠습니다...!

2024-11-03 11:57 UTC, junghwa1996 commented
@hwiiron 휘철님 죄송하지만 해당 이슈 기능 구현 좀 부탁드려도 될까요? 너무 늦어지고있어서요 한번 봐주세요🙏🏻

2024-11-03 12:01 UTC, Hogn-hyeonbin commented
> @hwiiron 휘철님 죄송하지만 해당 이슈 기능 구현 좀 부탁드려도 될까요? 너무 늦어지고있어서요 한번 봐주세요🙏🏻

저 이거 어제 다시 수정했긴 했는데 말씀을 안드렸었습니다 죄송합니다... 혹시 지금도  오류 발생하나요?

2024-11-03 12:08 UTC, junghwa1996 commented
> > @hwiiron 휘철님 죄송하지만 해당 이슈 기능 구현 좀 부탁드려도 될까요? 너무 늦어지고있어서요 한번 봐주세요🙏🏻
> 
> 저 이거 어제 다시 수정했긴 했는데 말씀을 안드렸었습니다 죄송합니다... 혹시 지금도 오류 발생하나요?

해당 github에서도 확인가능합니다
![image](https://github.com/user-attachments/assets/cffacec1-6c77-44ea-bfcd-da40acbb11b7)

2024-11-03 12:14 UTC, hwiiron commented
> @hwiiron 휘철님 죄송하지만 해당 이슈 기능 구현 좀 부탁드려도 될까요? 너무 늦어지고있어서요 한번 봐주세요🙏🏻

넵 확인했습니다!

2024-11-03 12:16 UTC, junghwa1996 commented
> > @hwiiron 휘철님 죄송하지만 해당 이슈 기능 구현 좀 부탁드려도 될까요? 너무 늦어지고있어서요 한번 봐주세요🙏🏻
> 
> 넵 확인했습니다!

@Hogn-hyeonbin 휘철님이 봐주신다고 합니다
@hwiiron 컴플릿 해결 후 정상동작 하는지 테스트 부탁드립니다

2024-11-03 12:36 UTC, Hogn-hyeonbin commented
> > > @hwiiron 휘철님 죄송하지만 해당 이슈 기능 구현 좀 부탁드려도 될까요? 너무 늦어지고있어서요 한번 봐주세요🙏🏻
> > 
> > 
> > 넵 확인했습니다!
> 
> @Hogn-hyeonbin 휘철님이 봐주신다고 합니다 @hwiiron 컴플릿 해결 후 정상동작 하는지 테스트 부탁드립니다

넵 알겠습니다

2024-11-04 16:19 UTC, hwiiron commented
무한 스크롤 기능 구현 완료되었습니다. 확인 부탁드립니다.

2024-11-04 18:46 UTC, junghwa1996 approved these changes
와우 미쳤당...최고 고생하셨어요!

2024-11-04 18:58 UTC, merged