✨ 삭제 기능 컴포넌트
codeit-sprint-part2-2team/rolling pull request #179
Opened 2024-10-31 15:43 UTC by Hogn-hyeonbin

#178 삭제 기능 컴포넌트

클릭 이벤트 발생 시 즉시 삭제 하는 기능.

다른 컴포넌트들과 통합과 적용이 잘될 수 있게 재사용성을 높였다.

2024-10-31 22:11 UTC, junghwa1996 requested changes
다시 작업해주세용 해당 기능 제가 올린기능에 붙혀서 PR 올려주세용

2024-11-01 03:24 UTC, junghwa1996 commented
> 다시 작업해주세용 해당 기능 제가 올린기능에 붙혀서 PR 올려주세용

이거 제가 합쳐보고 테스트하고 수정할부분있으면 요청드릴게요

2024-11-01 03:51 UTC, junghwa1996 commented
제가 삭제 기능 구현했습니다
- /post/{id}/edit으로 이동 후 삭제 버튼을 눌러서 삭제
- 삭제 완료 시 /post/{id}로 이동

2024-11-01 03:51 UTC, Hogn-hyeonbin commented
넵 확인 했습니다

2024-11-01 03:51 UTC, junghwa1996 commented
> 제가 삭제 기능 구현했습니다
> 
> * `/post/{id}/edit`으로 이동 후 삭제 버튼을 눌러서 삭제
> * 삭제 완료 시 `/post/{id}`로 이동

2024-11-01 03:55 UTC, swp91 approved these changes

2024-11-01 03:55 UTC, swp91 commented on src/components/MessagesCardList/MessageCardList.jsx
> +
확인했습니다👍

2024-11-01 03:57 UTC, hwiiron approved these changes
확인했습니다! 감사합니다!!

2024-11-01 03:57 UTC, Hogn-hyeonbin commented
그러면 저는 바로 수정하기 페이지 이동 시 데이터 가져오기 기능 작업하겠습니다.

2024-11-01 03:59 UTC, junghwa1996 requested changes
등록 확인했습니다!! 근데 폰트가 적용이 안되는것같습니다!!

2024-11-01 04:01 UTC, junghwa1996 commented
> 그러면 저는 바로 수정하기 페이지 이동 시 데이터 가져오기 기능 작업하겠습니다.

네넹~

2024-11-01 04:01 UTC, junghwa1996 approved these changes

2024-11-01 04:01 UTC, merged