Feature/#63 메인 페이지
codeit-sprint-part2-2team/rolling pull request #181
Opened 2024-10-31 17:28 UTC by mangmang1004

### 이슈 번호

#63

### 변경 사항 요약

ex) 로그인할 때, 카카오톡 로그인 기능을 추가했습니다.

- 작업 중입니당.. 

### 테스트 결과

베이스(develop) 브랜치에 포함되기 위한 코드는 모두 정상적으로 작동이 되어야 합니다.

ex) 결과물에 대한 스크린 샷

2024-10-31 22:12 UTC, junghwa1996 commented
아이고 PR을 올려달라는 뜻은 아니였는데..ㅎㅎ 그냥 여기서 계속 푸시하세용

2024-11-01 17:22 UTC, junghwa1996 requested changes

2024-11-01 17:22 UTC, junghwa1996 commented on src/pages/HomePage/HomePage.jsx
> +
배열로 텍스트 관리하신 아이디어 완전 대박적 👍🏻

2024-11-01 17:22 UTC, junghwa1996 commented on src/pages/HomePage/HomePage.jsx
> +  //TODO - 추후 리팩토링 과정 중 컴포넌트(카드 부분)로 뺄 수 있음 뺄 예정 !
재사용할 수 있는 컴포넌트는 아니라서 별도 분리는 안하셔도 될듯해요!

2024-11-01 17:22 UTC, junghwa1996 commented on src/pages/HomePage/HomePage.jsx
> +            생성하기
여기는 '구경해보기' 로 수정해주세용!

2024-11-01 17:22 UTC, junghwa1996 commented on src/pages/HomePage/HomePage.styles.js
> +  background-color: #f6f8ff; //따로 컬러 시스템 적용이 안되어 있음
이거는 `theme`에 `surface` 속성 쓰시면 됩니다!

2024-11-01 17:22 UTC, junghwa1996 commented on src/pages/HomePage/HomePage.styles.js
> +    color: #181818; //DarkMode로 변환이 되어있을 때, 흰색으로 변하게 되는데 배경색 때문에 묻힘
이것두 위에 리뷰 반영하면 bg바뀔거에요!! 얘도 `theme.text`사용해주세요!

2024-11-01 17:22 UTC, junghwa1996 commented on src/pages/HomePage/HomePage.styles.js
전체적으로 props로 컨트롤 되는 스타일빼고는 전부 module.css로 옮겨서 스타일 컴포넌트에 className으로 사용해주세요!
```javascript
<FeatTextContainer $index={index} className={styles.featContainer}>
```
이런 식으로!!

2024-11-01 17:57 UTC, mangmang1004 commented on src/pages/HomePage/HomePage.styles.js
제가 그런식으로 작업을 해봤는데 ! 우선순위가 엇갈리면서 styled component만 받아오고 module.css 안에 있는 내용은 하나도 받아오지 못하더라구여 ㅜㅠ @junghwa1996

2024-11-01 18:09 UTC, junghwa1996 commented on src/pages/HomePage/HomePage.styles.js
> 제가 그런식으로 작업을 해봤는데 ! 우선순위가 엇갈리면서 styled component만 받아오고 module.css 안에 있는 내용은 하나도 받아오지 못하더라구여 ㅜㅠ @junghwa1996

에????? 정말요?????????? 세상에 그런일이..................ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ 확인을 한번 해봐야겠군요 흑흑

2024-11-01 18:20 UTC, junghwa1996 requested changes

2024-11-01 18:20 UTC, junghwa1996 commented on src/pages/HomePage/HomePage.module.css
> +
앜ㅋㅋㅋㅋㅋㅋㅋㅋ 소망님 이건 sass 가 아니랍니다!! ㅎㅎ 너무 styled components에 익숙해지셨네용ㅋㅋㅋㅋㅋ

2024-11-01 18:22 UTC, mangmang1004 commented on src/pages/HomePage/HomePage.styles.js
뉑 ㅜㅠ 제가 한 2시간 넘게 시도하구 GPT랑도 싸우고 했는데,,, 계속 안먹어서 ㅜㅜㅠㅜㅠㅜㅠㅜㅠㅜㅠㅜㅠㅜㅠ

2024-11-01 18:23 UTC, junghwa1996 commented on src/pages/HomePage/HomePage.module.css
> +
css에서는 미디어쿼리를 쓸때 class를 붙혀줘야하고 지금 상속 식으로 작성이 되어있어서 하단으로 내려주세용!

2024-11-01 18:33 UTC, junghwa1996 commented on src/pages/HomePage/HomePage.styles.js
우리 소망님 가상 선택자도 다 까먹어부릇다...ㅎㅎㅎㅎㅎㅎㅎ

2024-11-01 18:33 UTC, junghwa1996 commented on src/pages/HomePage/HomePage.styles.js
제가 수정해서 푸시할테니까 그거한번보실래용?

2024-11-02 06:36 UTC, mangmang1004 reviewed
모든 상황 수정해서 반영했습니다 :-). 

@junghwa1996 확인해주시면 머지 하겠습니당

2024-11-02 11:06 UTC, junghwa1996 approved these changes
고생하셨어용~

2024-11-02 11:18 UTC, merged