Feature/#153 롤링 simple banner 드롭다운 기능
codeit-sprint-part2-2team/rolling pull request #209
Opened 2024-11-01 16:05 UTC by yongcheol-1

### 이슈 번호

close #153 

### 변경 사항 요약

Style 작업이 아직 안되어 있어 요청드립니다.

토스트가 화면 중간 하단에 토스트 메세지가 생성되고
공유하기 버튼과 드롭다운 기능 추가했습니다.

추후 카카오API를 통해 어떤 오브젝트를 공유할건지 논의가 필요합니다.

### 테스트 결과

베이스(develop) 브랜치에 포함되기 위한 코드는 모두 정상적으로 작동이 되어야 합니다.

ex) 결과물에 대한 스크린 샷
![공유 버튼](https://github.com/user-attachments/assets/c149a9da-24fc-4ecc-a6ed-e7e5f6186799)

![토스트 메세지](https://github.com/user-attachments/assets/3a056c22-3fbd-4127-9a7b-1f486cf86380)

2024-11-01 17:40 UTC, junghwa1996 requested changes
전체적으로 많이 고민하고 작성하신것같은게 딱 보이네요 ㅎㅎ
너무 고생많으셨습니다!!!

2024-11-01 17:40 UTC, junghwa1996 commented on src/App.jsx
기능 구현 테스트를 위해서 만드신걸까용?

2024-11-01 17:40 UTC, junghwa1996 commented on src/components/toast/Toast.Styles.js
> +
안쓰는 주석은 제거해주세요!

2024-11-01 17:40 UTC, junghwa1996 commented on src/components/toast/Toast.Styles.js
오 디자인 시스템으로 사용하려고 노력이 보이는 코드같아서 칭찬드립니당 👏🏻👏🏻👏🏻

2024-11-01 17:40 UTC, junghwa1996 commented on src/components/toast/Toast.jsx
> +import CopyUrl from './CopyUrl';
이건 컴포넌트가 아닌 함수니까 카멜로 `copyUrl` 로 변경해주시는게 좋을듯싶어요!

2024-11-01 17:40 UTC, junghwa1996 commented on src/components/toast/ToastMessages.jsx
> +import closeIcon from '../../assets/icon-close.svg';
svg파일은 상수니까 `ICON_CLOSE` 라고 하면 좋을 것 같습니다!

2024-11-01 17:40 UTC, junghwa1996 commented on src/layout/Emoji/KaKaoShare.js
api 작업 어려우셨을텐데 너무 잘해주셨어요 👍🏻
어떤 스타일로 보낼지는 미팅 진행하면서 결정되면 수정하는걸로 하시죠!!

2024-11-01 17:40 UTC, junghwa1996 commented on src/layout/Emoji/SharingSelector.jsx
> +import ShareIcon from '../../assets/icon-share-24.svg'; // 공유 아이콘 이미지
여기도 상수라서 ICON_SHARE 로 변경되면 좋을듯해용

2024-11-01 17:40 UTC, junghwa1996 commented on src/layout/Emoji/SharingSelector.jsx
> +    const urlToShare = 'https://example.com'; // 공유할 URL
이 부분은 추가적으로 만들어두신 `copyUrl` 유틸 함수 호출해서 넣으면 될것같네요!

2024-11-01 17:40 UTC, junghwa1996 commented on src/layout/Emoji/SharingSelector.jsx
> +    navigator.clipboard.writeText(urlToShare).then(() => {
이런식으로 클립보드를 사용할 수 있다는 점 배워갑니다 👍🏻

2024-11-01 17:40 UTC, junghwa1996 commented on src/layout/Emoji/SharingSelector.styles.js
요기는 리팩토링 진행하면서 .module.css로 변경해주세요 😊

2024-11-01 17:40 UTC, junghwa1996 commented on src/router/Content.jsx
>  import MessagesListPage from '../pages/MessagesList/MessagesListPage';
아이구 여기부분 ESLint 경고 떠서 지우신것같아용 해당 페이지는 현빈님이 추가로 작업 진행하시라고 놔둔 파일이에용~

2024-11-01 17:40 UTC, junghwa1996 commented on src/utils/themeUtils.js
이 파일은 이제 사용되지않습니다!! 삭제해서 푸시해주세요!

2024-11-02 10:34 UTC, junghwa1996 approved these changes

2024-11-02 10:52 UTC, yongcheol-1 commented
리뷰 사항반영, 스타일링이 요구사항과 같이 나오는것 확인하고 수정했습니다!

2024-11-02 10:54 UTC, junghwa1996 commented
> 리뷰 사항반영, 스타일링이 요구사항과 같이 나오는것 확인하고 수정했습니다!

그 리뷰어 한명이 더 필요해서 리마인드 언급주셔야할것같아요~

2024-11-02 10:56 UTC, hwiiron approved these changes
크흐 역시 용철님 해내셨군요!!!! 정말 너무너무 고생하셨습니다....👍

2024-11-02 10:59 UTC, merged