#208 components input file메시지 생성   프로필 선택
codeit-sprint-part2-2team/rolling pull request #212
Opened 2024-11-01 17:24 UTC by hwiiron

### 이슈 번호

close #208 

### 변경 사항 요약

정적 스타일 컴포넌트 코드들을 모듈 CSS로 전환하기 위해 코드 수정하였습니다.

2024-11-01 18:02 UTC, junghwa1996 requested changes
확실히 깔끔해졌네요 👍🏻

2024-11-01 18:02 UTC, junghwa1996 commented on src/components/InputFile/InputFile.styles.js
이건 코드가 짧아서 styles.js는 삭제하고 렌더 컴포넌트 본문에 넣으셔도될것같아요!

2024-11-01 18:28 UTC, hwiiron commented on src/components/InputFile/InputFile.styles.js
확인하고 수정했습니다!

2024-11-02 03:07 UTC, junghwa1996 approved these changes

2024-11-02 04:54 UTC, Hogn-hyeonbin approved these changes
확인했습니다

2024-11-02 05:02 UTC, merged