#198 components background selector롤링페이퍼 생성   배경화면 선택
codeit-sprint-part2-2team/rolling pull request #213
Opened 2024-11-01 17:54 UTC by hwiiron

### 이슈 번호

close #198

### 변경 사항 요약

정적 스타일 컴포넌트 코드들을 모듈 CSS로 전환하기 위해 코드 수정하였습니다.

2024-11-01 18:06 UTC, junghwa1996 requested changes

2024-11-01 18:06 UTC, junghwa1996 commented on src/components/BackgroundSelector/RadioCard.styles.js
여기도 동적인 요소는 안보여서 css로 작성해주시고 렌더 컴포넌트에 
```javascript
<button className={styles.button}>
  {selectedValue === item && <div className="icon"></div>}
</button>
```

이렇게 하는게 더좋을것같긴한데 혹시 저 `StyleButton`이 다른곳에서 호출되는거라 스타일 컴포넌트로 빼신걸까요??

2024-11-01 18:14 UTC, hwiiron commented on src/components/BackgroundSelector/RadioCard.styles.js
> 이렇게 하는게 더좋을것같긴한데 혹시 저 `StyleButton`이 다른곳에서 호출되는거라 스타일 컴포넌트로 빼신걸까요??

아 아닙니다! 제안해 주신 방법으로 수정하겠습니다!

2024-11-01 18:22 UTC, hwiiron commented on src/components/BackgroundSelector/RadioCard.styles.js
아 이 부분 확인해보니 코드가 접혀져 있어서 못보셨나봅니다.. 저도 이거 보고 엥 왜 이걸 안 뺏지...? 했었네요....😅
![Group 3](https://github.com/user-attachments/assets/4a5148e0-837a-4513-b249-e2ed955adda6)

2024-11-02 17:50 UTC, junghwa1996 approved these changes

2024-11-03 00:34 UTC, Hogn-hyeonbin approved these changes
확인했습니다!

2024-11-03 00:39 UTC, merged