Feature/#194 이모지 드롭다운 데이터 가져와서 보여주기
codeit-sprint-part2-2team/rolling pull request #215
Opened 2024-11-01 18:19 UTC by mangmang1004

### 이슈 번호

close #194 

### 변경 사항 요약

- get 이모지 요청
- 관련 UI 작업 + 반응형 포함 

> @junghwa1996 @용철 get 요청을 post와 동시에 작업을 해서 Post를 하면 이모지의 개수도 바뀔 테니, 그것을 이모지 드롭다운에 데이터를 뿌려주는 식으로 작업을 해야할 것 같습니다 ! ( 이미지 개수가 바뀌면 렌더링되는 형식으로 ) get 요청 했을 때 사용했던 함수 가져가서 조합 하면 될 것 같습니다. 

### 테스트 결과

베이스(develop) 브랜치에 포함되기 위한 코드는 모두 정상적으로 작동이 되어야 합니다.

#### PC
![image](https://github.com/user-attachments/assets/355462e1-db49-435a-a7c4-b8d46df22572)

#### 나머지
![image](https://github.com/user-attachments/assets/27f36445-a22b-43f9-8316-38eb0d85ea98)

2024-11-02 09:16 UTC, junghwa1996 requested changes

2024-11-02 09:16 UTC, junghwa1996 commented on src/layout/Emoji/EmojiDropDown.jsx
> +        setEmojiList(sortedData);
여기는 딱히 필요없을것같긴해요! 서버에서 기본값으로 내려주는게 인기순이라서요!

2024-11-02 11:19 UTC, mangmang1004 commented on src/layout/Emoji/EmojiDropDown.jsx
> +        setEmojiList(sortedData);
혹시나 좀 더 확실히 하기 위해서 넣긴 했는데 지울까융?!

2024-11-02 12:03 UTC, mangmang1004 commented
@swp91 

> post와 동시에 작업을 해서 post를 하면 이모지의 개수도 바뀔 테니, 그것을 이모지 드롭다운에 데이터를 뿌려주는 식으로 작업을 해야할 것 같습니다 ! ( 이미지 개수가 바뀌면 렌더링되는 형식으로 ) get 요청 했을 때 사용했던 함수 가져가서 조합 하면 될 것 같습니다.

제가 이부분을 고민해 봤는데 이 조합을 부모인 헤더에서 하는 게 맞는 거 같아서용 !

2024-11-02 12:06 UTC, junghwa1996 commented on src/layout/Emoji/EmojiDropDown.jsx
> +        setEmojiList(sortedData);
한번 헤더 연결하면서 테스트해보고 잘되면 그때 지우죠! 위에 확인사항으로 주석달아놔주세요 나중에 지울수있게!

2024-11-03 07:49 UTC, mangmang1004 reviewed
주석 추가 해두었습니다 ! 

@swp91 헤더 조합할 때 필히 필요하실 꺼 같아 얼른 머지를 시켜야 할 꺼 같네여 !

2024-11-03 09:13 UTC, junghwa1996 approved these changes

2024-11-03 12:17 UTC, merged