Feature/#202 components   tap toggle 탭 토글
codeit-sprint-part2-2team/rolling pull request #216
Opened 2024-11-01 21:53 UTC by Hogn-hyeonbin

### 탭 토글 기능 리팩토링

close #'202'

### 변경 사항 요약

1. 스타일 리팩토링
2. 정적인 부분은 모듈화로, 동적인 부분 스타일 컴포넌트 그대로 유지
3. 주석 첨가

2024-11-02 05:57 UTC, hwiiron commented
그리고 `TapToggle.module.css`로 파일명 만들어주셨던데 `TabToggle.module.css`로 부탁드릴게요!
감사합니다!!

2024-11-02 06:49 UTC, mangmang1004 approved these changes

2024-11-02 06:49 UTC, mangmang1004 commented on src/components/TabToggle/TabToggle.jsx
주석 깔끔하게 달아놓는 거 좋습니당 😆

2024-11-02 07:09 UTC, Hogn-hyeonbin commented
넵 확인해 보고 수정하겠습니다!!

2024-11-02 10:37 UTC, junghwa1996 requested changes

2024-11-02 10:37 UTC, junghwa1996 commented on src/components/TabToggle/TabToggle.styles.js
>    transition: left 0.3s ease;
여기서 동적인 요소만 남겨두고 나머지는 css로 옮겨주세요!

2024-11-02 18:57 UTC, Hogn-hyeonbin commented on src/components/TabToggle/TabToggle.styles.js
>    transition: left 0.3s ease;
넵 수정했습니다

2024-11-02 18:58 UTC, Hogn-hyeonbin commented
> 그리고 `TapToggle.module.css`로 파일명 만들어주셨던데 `TabToggle.module.css`로 부탁드릴게요! 감사합니다!!

넵 수정했습니다 혹시 오류 계속 나오면 말씀 주세요!

2024-11-03 00:54 UTC, hwiiron approved these changes
확인했습니다!! 수정 감사합니다!👍

2024-11-03 12:18 UTC, junghwa1996 approved these changes

2024-11-03 12:19 UTC, merged