Feature/#222 component   drop down 스타일 분리 및 전체적인 스타일 변수 정리
codeit-sprint-part2-2team/rolling pull request #230
Opened 2024-11-02 12:31 UTC by mangmang1004

### 이슈 번호

close #222 

### 변경 사항 요약

- [x] Dropdown.module.css
- [x] Dropdown.styles.js
- [x] Input.module.css
- [x] Input.styles.js

### 테스트 결과

베이스(develop) 브랜치에 포함되기 위한 코드는 모두 정상적으로 작동이 되어야 합니다.

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/a3ee2d7a-9427-4972-8089-b7e993f30815">

2024-11-02 13:15 UTC, yongcheol-1 commented
확인했습니다!

2024-11-02 13:34 UTC, junghwa1996 requested changes

2024-11-02 13:34 UTC, junghwa1996 commented on src/components/TextField/Dropdown.jsx
>  import ArrowTop from '../../assets/icon-arrow_top.svg';
이거 굳이 두개로 나눌 필요없고 하나만해서 `transform` 이용해서 돌려쓰는게 좋을듯해요~
그리고 이미지 변수명은 상수로 변경 부탁드립니다!

2024-11-03 12:19 UTC, junghwa1996 commented on src/components/TextField/Dropdown.jsx
>  import ArrowTop from '../../assets/icon-arrow_top.svg';
수정 됐을까요?

2024-11-03 14:21 UTC, mangmang1004 commented on src/components/TextField/Dropdown.jsx
>  import ArrowTop from '../../assets/icon-arrow_top.svg';
수정 완료했습니다 !!

2024-11-03 14:34 UTC, junghwa1996 approved these changes

2024-11-03 19:27 UTC, merged