Feature/#200 components toast토스트
codeit-sprint-part2-2team/rolling pull request #231
Opened 2024-11-02 13:13 UTC by yongcheol-1

### 이슈 번호

close #200 

### 변경 사항 요약

Toast.jsx 파일에서 StyledToastContainer로 반환되는 부분을 ToastContainer로 수정
Toast.moduel.css 파일 생성후 수정

CopyUrl.jsx , ToastMesasages.jsx는 수정X 변경사항 없음

그 외 Toast기능을 사용하는 SharingSelector.jsx에서도 작동

### 테스트 결과

2024-11-02 13:37 UTC, junghwa1996 requested changes

2024-11-02 13:37 UTC, junghwa1996 commented on src/layout/Emoji/SharingSelector.module.css
안에 내용없는 파일이면 삭제해주세요~

2024-11-02 14:29 UTC, junghwa1996 commented on src/layout/Emoji/SharingSelector.module.css
수정하신거면 댓글남겨주세요 알람이 안떠서 수정완료하셨는지 체크가 안됩니다 커밋보니까 수정하신것같은데 완료된게 맞을까요?

2024-11-03 04:12 UTC, yongcheol-1 commented
넵 수정완료했습니다! 어제 댓글달아서올렸는데 제가 뭘잘못눌렀는지 댓글이 안올라간거같아요 늦게 답드려서 죄송합니다..ㅠㅠ

2024-11-03 10:55 UTC, yongcheol-1 commented
파일 최종수정 완료했습니다!

2024-11-03 11:24 UTC, junghwa1996 commented
수정된건가요? 수정 코멘트 남기신것같은데 지금은 안보이네요~

2024-11-03 20:45 UTC, yongcheol-1 commented
1. 요구된 스타일대로 Toast스타일링 되었습니다
2. Toast 기능과 확인했습니다.
3. 콘솔창 URL 공유 클릭시 복사, 카카오톡 공유시 API연결되어서 콘솔창과 카카오로그인창 뜨는거 확인했습니다.

2024-11-04 05:37 UTC, junghwa1996 commented
![image](https://github.com/user-attachments/assets/be50ffa5-e299-4841-a94d-9a82343ee6a1)
## 이슈

- [ ] 모바일에서 레이아웃 조금 깨져요

- [ ] 팝업 올라오고 다시 공유하기 눌렀을때 팝업이 사라졌다가 다시나오는 이상현상 발견

2024-11-04 06:49 UTC, yongcheol-1 commented
확인하고 이슈 수정하겠습니다.

2024-11-04 14:25 UTC, junghwa1996 approved these changes

2024-11-04 14:49 UTC, hwiiron approved these changes
결국 완성하셨네요!!! 열심히 해주셔서 감사합니다!!!!👍

2024-11-04 15:52 UTC, yongcheol-1 commented
현재 테블릿,모바일,PC 환경에서 레이아웃 깨지지않고 Toast메세지 잘출력되고있습니다!

모바일에서 팝업올라오고 공유하기눌렀을때 팝업 사라졌다 나오는 이상이슈는

드롭다운 리스트가 레이아웃밖으로 나가면서 UI가 깨지는현상인것같아 
소망님께 작업요청드렸습니다!

반영되는대로 확인하고 수정하겠습니다.

2024-11-04 17:15 UTC, yongcheol-1 commented
소망님이 수정하신 코드 넣고 확인 테블릿,PC,모바일 문제없이 동작합니다!

2024-11-04 18:55 UTC, junghwa1996 commented
![image](https://github.com/user-attachments/assets/22569124-f344-4550-bdfd-c7abdea81db6)
컴플릿났어요 이거 소망님께 확인하고 확인되면 머지 하세요

2024-11-04 19:28 UTC, yongcheol-1 commented
넵 알겠습니다

2024-11-05 05:29 UTC, merged