#232_component---EmojiBadge
codeit-sprint-part2-2team/rolling pull request #233
Opened 2024-11-02 14:00 UTC by mangmang1004

css 모듈 화면으로 분리

### 이슈 번호

close #232 

### 변경 사항 요약

ex) 로그인할 때, 카카오톡 로그인 기능을 추가했습니다.

- [x] EmojiBadge.module.css
- [x] EmojiBadge.styles.js

### 테스트 결과

베이스(develop) 브랜치에 포함되기 위한 코드는 모두 정상적으로 작동이 되어야 합니다.

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/f8405734-7c15-4b85-916a-86aca45677ae">

2024-11-02 14:28 UTC, junghwa1996 requested changes

2024-11-02 14:28 UTC, junghwa1996 commented on src/components/Badge/EmojiBadge.styles.js
이거는 jsx 파일 내부로 옮겨주세요!

2024-11-03 07:29 UTC, mangmang1004 commented on src/components/Badge/EmojiBadge.styles.js
해결했습니다 :-)

2024-11-03 07:37 UTC, mangmang1004 reviewed
모두 정리 해두었습니당 🫡

2024-11-03 12:20 UTC, junghwa1996 approved these changes

2024-11-03 12:21 UTC, merged